# **IMPORT NUMPY**

In [2]:
import numpy as np

**NumPy array** is a fast, memory-efficient grid of values. A **1D array** is like a single row of numbers, similar to a Python list but much faster for mathematical operations.

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

**2D array** is like a table with rows and columns, similar to a matrix in mathematics.


In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**3D array** is like a cube of numbers — multiple 2D arrays stacked together. Think of it as multiple tables/matrices combined.


In [4]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

**`type()`** returns the data type of any variable. For all NumPy arrays it will show `<class 'numpy.ndarray'>` — ndarray means N-dimensional array.

In [7]:
print(type(arr))
print(type(arr_2d))
print(type(arr_3d))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


**`ndim`** returns the number of dimensions of a NumPy array.


In [8]:
print(arr.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

1
2
3


**`shape`** returns the size of each dimension as `(rows, columns)` for 2D and `(depth, rows, columns)` for 3D.


In [9]:
print(arr.shape)
print(arr_2d.shape)
print(arr_3d.shape)

(5,)
(3, 3)
(2, 2, 3)


**`size`** returns the total number of elements in the array.


In [10]:
print(arr.size)
print(arr_2d.size)
print(arr_3d.size)

5
9
12


**`dtype`** returns the data type of the elements stored in the NumPy array.


In [11]:
print(arr.dtype)
print(arr_2d.dtype)
print(arr_3d.dtype)

int64
int64
int64


**`sum(axis=1)`** adds values **row wise** — meaning it sums across columns for each row.


In [12]:
print(arr_2d.sum(axis=1))

[ 6 15 24]


**`sum(axis=0)`** adds values **column wise** — meaning it sums across rows for each column.


In [13]:
print(arr_2d.sum(axis=0))

[12 15 18]


# Built in Array

**1. np.zeros()** — All element 0

Creates an array filled with zeros of given shape.

In [14]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**2. np.ones()** — All element 1

Creates an array filled with ones of given shape.

In [15]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**3. np.full()**— Fillup using any value

Creates an array filled with a specific value.

In [16]:
np.full((3, 4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

**4. np.eye()** — Identity matrix

Creates a square matrix with 1s on the diagonal and 0s elsewhere.

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**5. np.empty()** — Empty matrix

Creates an uninitialized array — values are random garbage from memory.

In [18]:
np.empty((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**6. np.arange()**— Range of values

Creates an array with evenly spaced values within a given range.

In [19]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


**7. np.linspace()** — Fixed number of values

Creates an array with a fixed number of evenly spaced values between two points.

In [20]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

**8. np.random.rand()**— Random float values (0 to 1)

Creates an array with random float values between 0 and 1.

In [21]:
np.random.rand(3, 4)

array([[0.79281773, 0.97870942, 0.15148442, 0.55710157],
       [0.26567748, 0.06389003, 0.01481775, 0.14144066],
       [0.72109989, 0.48545601, 0.87677684, 0.29958371]])

**9. np.random.randint()**— Random integer values

Creates an array with random integers between a given range.

In [25]:
np.random.randint(0, 100, (5, 6))

array([[71, 15, 57, 26, 28, 99],
       [77, 89, 61, 24, 95, 22],
       [12,  4, 49, 36, 91, 30],
       [54, 49, 42, 96,  6, 93],
       [21, 65, 95, 38, 78, 68]])

**10. np.random.randn()** — Random normal distribution
Creates an array with random values following a normal/gaussian distribution.

In [23]:
np.random.randn(3, 4)

array([[ 1.59182873e-02,  1.25736048e+00,  1.49098036e+00,
         2.13113853e+00],
       [ 8.22878335e-01,  5.33711118e-01,  3.73312503e-04,
         1.40723068e+00],
       [ 1.19078410e+00,  2.90844026e-01, -1.80971301e-01,
         7.35388716e-01]])

# Indexing, Slicing & Flatten

In [26]:
rand_arr = np.random.randint(0, 100, (5, 6))
rand_arr

array([[35, 13, 95, 42, 58, 48],
       [12, 91, 84, 71, 64,  1],
       [41, 62, 77, 94, 58, 98],
       [21,  2, 63, 91, 98, 56],
       [88, 46, 37, 35, 53, 41]])

**Indexing** accesses a single specific element using its row and column position.



In [27]:
rand_arr[0, 0]   # first row, first column

np.int64(35)

In [28]:
rand_arr[2, 3]   # third row, fourth column

np.int64(94)

In [29]:
rand_arr[-1, -1] # last row, last column

np.int64(41)

**Slicing** accesses a range of rows and/or columns using : operator.

In [30]:
rand_arr[0:2]         # first 2 rows

array([[35, 13, 95, 42, 58, 48],
       [12, 91, 84, 71, 64,  1]])

In [31]:
rand_arr[:, 0:3]      # all rows, first 3 columns

array([[35, 13, 95],
       [12, 91, 84],
       [41, 62, 77],
       [21,  2, 63],
       [88, 46, 37]])

In [32]:
rand_arr[1:3, 2:5]    # row 1-2, column 2-4

array([[84, 71, 64],
       [77, 94, 58]])

**`flatten()`** converts any multi-dimensional array into a single 1D array.


In [33]:
rand_arr.flatten()

array([35, 13, 95, 42, 58, 48, 12, 91, 84, 71, 64,  1, 41, 62, 77, 94, 58,
       98, 21,  2, 63, 91, 98, 56, 88, 46, 37, 35, 53, 41])

In [34]:
rand_arr.shape

(5, 6)

# Stacking

**Stacking** combines two or more arrays together. **Vertical stacking** adds rows on top of each other, **Horizontal stacking** adds columns side by side.

In [36]:
arr1 = np.random.randint(0, 100, (5, 6))
arr2 = np.random.randint(0, 100, (5, 6))

In [37]:
arr1

array([[57, 98, 25, 89, 61, 73],
       [55,  5, 64, 23, 10, 34],
       [27, 15, 81, 80, 74,  8],
       [17, 95, 69,  6,  1, 97],
       [72, 14, 12, 68, 79, 20]])

In [38]:
arr2

array([[36, 42, 32, 76,  1, 72],
       [40,  2, 95, 66, 59, 56],
       [73, 81, 93, 77, 63, 26],
       [30, 49, 93, 57, 61, 59],
       [99, 91, 19, 95, 76, 26]])

**Vertical stacking — `vstack()`**


In [39]:
v_stack = np.vstack((arr1, arr2))
v_stack

array([[57, 98, 25, 89, 61, 73],
       [55,  5, 64, 23, 10, 34],
       [27, 15, 81, 80, 74,  8],
       [17, 95, 69,  6,  1, 97],
       [72, 14, 12, 68, 79, 20],
       [36, 42, 32, 76,  1, 72],
       [40,  2, 95, 66, 59, 56],
       [73, 81, 93, 77, 63, 26],
       [30, 49, 93, 57, 61, 59],
       [99, 91, 19, 95, 76, 26]])

**Horizontal stacking — `hstack()`**


In [40]:
h_stack = np.hstack((arr1, arr2))
h_stack

array([[57, 98, 25, 89, 61, 73, 36, 42, 32, 76,  1, 72],
       [55,  5, 64, 23, 10, 34, 40,  2, 95, 66, 59, 56],
       [27, 15, 81, 80, 74,  8, 73, 81, 93, 77, 63, 26],
       [17, 95, 69,  6,  1, 97, 30, 49, 93, 57, 61, 59],
       [72, 14, 12, 68, 79, 20, 99, 91, 19, 95, 76, 26]])

**`transpose()`** flips the array — rows become columns and columns become rows.


In [41]:
arr1.T

array([[57, 55, 27, 17, 72],
       [98,  5, 15, 95, 14],
       [25, 64, 81, 69, 12],
       [89, 23, 80,  6, 68],
       [61, 10, 74,  1, 79],
       [73, 34,  8, 97, 20]])

**`np.random.randint()`** creates a random array. **`**2`** squares each element and **`np.sqrt()`** takes the square root of each element.



In [42]:
rand_arr = np.random.randint(1, 10, (3, 3))
print("Before:", rand_arr)

Before: [[7 2 2]
 [7 9 7]
 [4 1 7]]


**Square**

In [43]:
squared = rand_arr ** 2
print("Squared:", squared)

Squared: [[49  4  4]
 [49 81 49]
 [16  1 49]]


**Root**

In [44]:
rooted = np.sqrt(rand_arr)
print("Square Root:", rooted)

Square Root: [[2.64575131 1.41421356 1.41421356]
 [2.64575131 3.         2.64575131]
 [2.         1.         2.64575131]]


# Addition, Substraction, Multiplication, Division

**Element wise operations** in NumPy work directly between two arrays — each element of one array is operated with the corresponding element of the other array at the same position.

In [45]:
a = np.random.randint(1, 10, (3, 3))
b = np.random.randint(1, 10, (3, 3))

print("A:\n", a)
print("B:\n", b)

A:
 [[4 5 7]
 [2 8 9]
 [6 5 6]]
B:
 [[1 3 9]
 [1 1 8]
 [5 1 6]]


**Addition**

In [46]:
print("Sum:\n", a + b)

Sum:
 [[ 5  8 16]
 [ 3  9 17]
 [11  6 12]]


**Substraction**

In [47]:
print("Subtract:\n", a - b)

Subtract:
 [[ 3  2 -2]
 [ 1  7  1]
 [ 1  4  0]]


**Multiplication**

In [50]:
print("Multiply:\n", a * b)

Multiply:
 [[ 4 15 63]
 [ 2  8 72]
 [30  5 36]]


**Division**

In [49]:
print("Division:\n", a / b)

Division:
 [[4.         1.66666667 0.77777778]
 [2.         8.         1.125     ]
 [1.2        5.         1.        ]]


# Describe as Pandas

**`np.dot()`** multiplies two arrays following matrix multiplication rules — not element wise. **`mean()`**, **`median()`**, **`std()`** give statistical summaries. **`min()`** and **`max()`** return the smallest and largest values.


In [51]:
a = np.random.randint(1, 100, (4, 5))
b = np.random.randint(1, 100, (5, 4))

print("A:\n", a)
print("B:\n", b)

A:
 [[65  6 31  4 59]
 [32 46 54 42 87]
 [37  1 23 47 47]
 [28 47 64  4 31]]
B:
 [[47 89 30 25]
 [19 90 81 35]
 [30  7 30 46]
 [86 43 51 53]
 [77  7 22 82]]


**Dot Product**

In [52]:
print("Dot Product:\n", np.dot(a, b))

Dot Product:
 [[ 8986  7127  4868  8311]
 [14309  9781 10362 14254]
 [10109  5894  5312  8363]
 [ 6860  7559  7453  8043]]


**Mean**

In [53]:
print("Mean:", a.mean())

Mean: 37.75


**Median**

In [54]:
print("Median:", np.median(a))

Median: 39.5


**Standard Devation**

In [55]:
print("Standard Deviation:", a.std())

Standard Deviation: 22.349216988521096


**Minimum**

In [56]:
print("Min:", a.min())

Min: 1


**Maximum**

In [57]:
print("Max:", a.max())

Max: 87


#  Accuracy

**`np.array_equal()`** checks if two arrays are exactly equal. **`np.sum(a == b)`** counts how many elements match at the same position, giving the accuracy of the match.


In [58]:
x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, (3, 3))

print("X:\n", x)
print("Y:\n", y)

X:
 [[9 1 3]
 [9 1 3]
 [9 8 3]]
Y:
 [[5 8 9]
 [9 3 8]
 [8 2 5]]


**Same Check**

In [59]:
print("Are they equal:", np.array_equal(x, y))

Are they equal: False


**Accuracy Check**

In [60]:
matched = np.sum(x == y)
total = x.size
print("Matched elements:", matched)
print("Accuracy:", matched/total * 100, "%")

Matched elements: 1
Accuracy: 11.11111111111111 %


# Nul Value Check

**`np.isnan()`** checks for null/NaN values in a NumPy array and returns True where NaN exists.


In [61]:
print("Null check:\n", np.isnan(x))
print("Total nulls:", np.sum(np.isnan(x)))

Null check:
 [[False False False]
 [False False False]
 [False False False]]
Total nulls: 0


# Broadcasting

**Broadcasting** allows NumPy to perform operations on arrays of different shapes. The smaller array is automatically "stretched" to match the shape of the larger array without copying data.


In [62]:
p = np.random.randint(1, 10, (4, 3))
q = np.random.randint(1, 10, (1, 3))

print("P:\n", p)
print("Q:\n", q)

P:
 [[7 1 1]
 [8 1 9]
 [4 5 3]
 [5 1 7]]
Q:
 [[5 8 8]]


In [63]:
result = p + q
print("Broadcasting Result:\n", result)

Broadcasting Result:
 [[12  9  9]
 [13  9 17]
 [ 9 13 11]
 [10  9 15]]


# NaN to Num

**`np.nan_to_num()`** replaces NaN values with 0 by default, and infinity values with a large finite number.


In [64]:
arr_with_nan = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])
print("Before:", arr_with_nan)

Before: [ 1.  2. nan  4. nan  6.]


In [65]:
cleaned = np.nan_to_num(arr_with_nan)
print("After:", cleaned)

After: [1. 2. 0. 4. 0. 6.]


# Save & Load

**`np.save()`** saves a NumPy array to a `.npy` file and **`np.load()`** loads it back. This is useful when you want to reuse arrays without recreating them.


In [68]:
p

array([[7, 1, 1],
       [8, 1, 9],
       [4, 5, 3],
       [5, 1, 7]])

**Save**

In [66]:
np.save('my_array.npy', p)
print("Array saved!")

Array saved!


**Load**

In [67]:
loaded_arr = np.load('my_array.npy')
print("Loaded Array:\n", loaded_arr)

Loaded Array:
 [[7 1 1]
 [8 1 9]
 [4 5 3]
 [5 1 7]]
